
// List of GPIOS
#define GPIO_00_free1                           00
#define GPIO_01_free                            01
#define GPIO_02_free                            02
#define GPIO_03_free                            03
#define GIOP_THD_Sensor                         04
#define GPIO_05_free                            05
#define GPIO_06_free                            06
#define GPIO_07_free                            07
#define GPIO_08_free                            08
#define GPIO_09_free                            09
#define GPIO_10_free                            10
#define GPIO_11_free                            11
#define GPIO_12_free                            12
#define GPIO_13_free                            13
#define GPIO_14_free                            14
#define GPIO_15_free                            15
#define GPIO_16_free                            16
#define GPIO_17_free                            17
#define GPIO_18_free                            18
#define GPIO_Default_USB_D_Negative             19
#define GPIO_Default_USB_D_Positive             20
#define GPIO_21_free                            21
#define GPIO_NotAvailable01                     22
#define GPIO_NotAvailable02                     23
#define GPIO_NotAvailable03                     24
#define GPIO_NotAvailable04                     25
#define GPIO_Default_SPICS1                     26
#define GPIO_Default_SPIHD                      27
#define GPIO_Default_SPIWP                      28
#define GPIO_Default_SPICS0                     29
#define GPIO_Default_SPICLK                     30
#define GPIO_Default_SPIQ                       31
#define GPIO_Default_SPID                       32
#define GPIO_Inaccessible_on_DevKit_01          33
#define GPIO_Inaccessible_on_DevKit_02          34
#define GPIO_Default_Octal_PSRAM_01             35
#define GPIO_Default_Octal_PSRAM_02             36
#define GPIO_Default_Octal_PSRAM_03             37
#define GPIO_38_free                            38
#define GPIO_39_free                            39
#define GPIO_40_free                            40
#define GPIO_41_free                            41
#define GPIO_42_free                            42
#define GPIO_Default_U0_TXD                     43
#define GPIO_Default_U0_RXD                     44
#define GPIO_45_free                            45
#define GPIO_46_free                            46
#define GPIO_47_free                            47
#define GPIO_Default_RGB_LED                    48